name: hu-neuro-pipeline
channels:
  - conda-forge
  - defaults
dependencies:
  - ipykernel
  - jupytext
  - myst-nb
  - pip
  - python=3.11
  - quarto=1.4.550
  - r-base
  - r-dplyr
  - r-ggplot2
  - r-irkernel
  - r-lme4
  - r-reticulate
  - r-rmisc
  - seaborn
  - sphinx-book-theme=0.3.3
  - sphinx-copybutton
  - sphinx-gallery=0.7.0
  - sphinxcontrib-bibtex
  - pip:
      - pybtex-apa-style
      - sphinxcontrib-apa
