name: Build Sphinx docs ðŸ“„

on:
  push

jobs:
    job-name:
        runs-on: 'ubuntu-latest'
        steps:
          - uses: actions/checkout@v2
          # Builds the documentation package using the standard configuration
          - uses: cascode-labs/build-sphinx-action/action.yml@v0
